name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: 'Test Case: AlphaBeta (15)'
      id: test-case-alphabeta-15
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: 'Test Case: AlphaBeta (15)'
        setup-command: ''
        command: python3 solution.py
        input: '15'
        expected-output: AlphaBeta
        comparison-method: contains
        timeout: 1
        max-score: 14
    - name: Git Workflow Architecture Check
      id: git-workflow-architecture-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Git Workflow Architecture Check
        setup-command: git fetch --all
        command: '# 1. Verify the feature branch exists in history git branch -r |
          grep -q "origin/feature/fizzbuzz-logic" || { echo "Missing feature branch";
          exit 1; }  # 2. Verify the hotfix branch exists in history git branch -r
          | grep -q "origin/hotfix/input-validation" || { echo "Missing hotfix branch";
          exit 1; }  # 3. Verify that a Pull Request / Merge commit fingerprint exists
          on main git log --grep="Merge" -n 1 || { echo "No merge commit found. Did
          you use a Pull Request?"; exit 1; }'
        timeout: 1
        max-score: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CASE-ALPHABETA-15_RESULTS: "${{steps.test-case-alphabeta-15.outputs.result}}"
        GIT-WORKFLOW-ARCHITECTURE-CHECK_RESULTS: "${{steps.git-workflow-architecture-check.outputs.result}}"
      with:
        runners: test-case-alphabeta-15,git-workflow-architecture-check
